[package]
name = "float8-experiments"
version = "0.1.0"
edition = "2021"
description = "A project for testing float8 embeddings for KNN search"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
license = "Apache-2.0"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
float8 = "0.2.1"
npyz = "0.8.4"
ordered-float = "5.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.8"



[dev-dependencies]
criterion = "0.5"

